# Danube cluster name
cluster_name: "MY_CLUSTER"

# Danube Broker hostname
# Hostname or IP address shared by Broker, Admin API, and Prometheus exporter
broker_host: "0.0.0.0"

# Ports for the Danube broker services
# Port for gRPC communication with the broker
broker_port: 6650
# Port for the Admin API
admin_port: 50051
# Port for Prometheus exporter
prom_port: 9040

# Metadata Persistent Store address (e.g., etcd)
# Hostname or IP for etcd
meta_store_host: "127.0.0.1"
# Port for etcd or metadata store
meta_store_port: 2379

# Namespaces to be created on boot
bootstrap_namespaces:
  - "default"

# Broker policies, that can be overwritten by namespace / topic policies
policies:
  # Limits the maximum number of producers that can simultaneously publish messages to a specific topic.
  # Default is 0, unlimited.
  max_producers_per_topic: 0

  # Limits the maximum number of subscriptions that can be created on the topic.
  # Default is 0, unlimited.
  max_subscriptions_per_topic: 0

  # Limits the maximum number of consumers that can simultaneously consume messages from a specific topic.
  # Default is 0, unlimited.
  max_consumers_per_topic: 0

  # Limits the maximum number of consumers that can simultaneously use a single subscription on a topic.
  # Default is 0, unlimited.
  max_consumers_per_subscription: 0

  # Defines the Max publish rate (number of messages and/or bytes per second) for producers publishing to the topic.
  # Default is 0, unlimited.
  max_publish_rate: 0

  # Defines the Max dispatch rate (number of messages and/or bytes per second) for the topic.
  # Default is 0, unlimited.
  max_dispatch_rate: 0

  # Defines the dispatch rate for each subscription on the topic.
  # Default is 0, unlimited.
  max_subscription_dispatch_rate: 0

  # Limits the maximum size of a single message that can be published to the topic.
  # Default is 10 MB
  max_message_size: 10485760 # in bytes which means 10 MB
