version: "3.8"

services:
  # Define 3 ETCD nodes
  etcd1:
    image: quay.io/coreos/etcd:latest
    restart: unless-stopped
    environment:
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_CLUSTER=etcd1:2380,etcd2:2381,etcd3:2382
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
    ports:
      - "2379:2379"
      - "2380:2380"
  etcd2:
    image: quay.io/coreos/etcd:latest
    restart: unless-stopped
    environment:
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_CLUSTER=etcd1:2380,etcd2:2381,etcd3:2382
      - ETCD_INITIAL_CLUSTER_STATE=existing
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2381
    ports:
      - "2379:2379"
      - "2381:2380"
  etcd3:
    image: quay.io/coreos/etcd:latest
    restart: unless-stopped
    environment:
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_CLUSTER=etcd1:2380,etcd2:2381,etcd3:2382
      - ETCD_INITIAL_CLUSTER_STATE=existing
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2382
    ports:
      - "2379:2379"
      - "2382:2380"

# Persist ETCD data on local volumes (modify paths if needed)
volumes:
  etcd1-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /path/to/etcd1/data
  etcd2-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /path/to/etcd2/data
  etcd3-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /path/to/etcd3/data
