name: Unit Tests

on:
  push:
    branches:
      - 'main'  # This will trigger on push on main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Run broker tests
        run: cargo test --bin danube-broker

      - name: Run library tests
        run: |
          cargo test --lib -p danube-reliable-dispatch
          cargo test --lib -p danube-client
